spring.application.name=BusTicketBooking

spring.datasource.url=jdbc:postgresql://localhost:5432/busbookingdb
spring.datasource.username=postgres
spring.datasource.password=7896

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true